### ISSUE TITLE
Levantar os requisitos do domínio/problema do sistema

### ISSUE THREAD

**Issue by fabriciofx** [fabriciofx/ta-integrado#2]
Fazer reuniões com o cliente para entender o problema e começar a esboçar definir o escopo e os casos de uso do sistema.

**Comment by rupertcoder** [comment]
Quais são os dias que o cliente está disponível? Quantos casos de uso precisam ser feitos?

**Comment by fabriciofx** [comment]
@rupertcoder Precisa detalhar melhor os requisitos.

**Comment by fabriciofx** [comment]
@rupertcoder De acordo.
